module.exports = {
  firstTestCase: {
    operations: [
      'ReadRows',
      'ReadRows',
      'AddRow',
      'ReadRows',
      'Set',
      'ReadRows',
      'DeleteCells',
      'ReadRows',
      'DeleteRow',
      'ReadRows'
    ],
    movies: [
      { year: 2010 },
      { year: 2018 },
      {
        title: 'New Movie',
        year: 2020,
        imdb_title_id: 'tt31561181132',
        original_title: 'Misery',
        date_published: '2021-06-07',
        genre: 'Drama, Tragedy',
        duration: 20,
        country: 'Egypt',
        language: 'Arabic',
        director: 'NO one',
        writer: 'The best',
        production_company: 'CMP Faculty of engineering',
        actors: 'No actors',
        description: 'No life',
        avg_vote: 10,
        votes: 73,
        budget: 0,
        usa_gross_income: '',
        worldwide_gross_income: '',
        metascore: null,
        reviews_from_users: 8,
        reviews_from_critics: null
      },
      {
        title: 'New Movie',
        year: 2020
      },
      {
        title: 'New Movie',
        year: 2020,
        imdb_title_id: 'tt31561181132',
        original_title: 'Misery',
        date_published: '2021-06-07',
        genre: 'Comedy',
        description: 'No life',
        avg_vote: 8.4,
        votes: 342,
        budget: 0,
        usa_gross_income: '',
        worldwide_gross_income: '',
        metascore: null,
        reviews_from_users: 8,
        reviews_from_critics: null
      },
      {
        title: 'New Movie',
        year: 2020
      },
      {
        title: 'New Movie',
        year: 2020
      },
      {
        title: 'New Movie',
        year: 2020
      },
      {
        title: 'New Movie',
        year: 2020
      },
      {
        title: 'New Movie',
        year: 2020
      }
    ],
    cells: [
      [],
      [],
      [],
      [],
      [],
      [],
      ['usa_gross_income', 'worldwide_gross_income', 'metascore', 'reviews_from_users', 'reviews_from_critics'],
      [],
      [],
      []
    ]
  },
  secondTestcase: {
    operations: [
      "Set",
      "ReadRows",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
      "AddRow",
    ],
    movies: [
      {
        title: "Inception",
        year: "2012",
      },
      {
        title: "Inception",
        year: "2012",
      },
      {
        imdb_title_id: "tt0993840",
        title: "Army of the Dead",
        original_title: "Army of the Dead",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt11083552",
        title: "Wrath of Man",
        original_title: "Wrath of Man",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt6111574",
        title: "The Woman in the Window",
        original_title: "The Woman in the Window",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt10342730",
        title: "Spiral",
        original_title: "Spiral",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt7888964",
        title: "Nobody",
        original_title: "Nobody",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt0993840",
        title: "Army of the Dead",
        original_title: "Army of the Dead",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt11083552",
        title: "Wrath of Man",
        original_title: "Wrath of Man",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt6111574",
        title: "The Woman in the Window",
        original_title: "The Woman in the Window",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt10342730",
        title: "Spiral",
        original_title: "Spiral",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt7888964",
        title: "Nobody",
        original_title: "Nobody",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt0993840",
        title: "Army of the Dead",
        original_title: "Army of the Dead",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt11083552",
        title: "Wrath of Man",
        original_title: "Wrath of Man",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt6111574",
        title: "The Woman in the Window",
        original_title: "The Woman in the Window",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt10342730",
        title: "Spiral",
        original_title: "Spiral",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
      {
        imdb_title_id: "tt7888964",
        title: "Nobody",
        original_title: "Nobody",
        year: "2021",
        date_published: "2021-03-29",
        genre: "Action",
        duration: 150,
        country: "America",
        language: "English",
        director: "Ahmed Sherif",
        writer: "Ahmed Ashraf",
        production_company: "Islam Ahmed Production",
        actors: "Khalid Ali",
        description: "A team from CMP tries to survive the college",
        avg_vote: 10,
        votes: 76,
        budget: "",
        usa_gross_income: "",
        worlwide_gross_income: "$ 3564",
        metascore: null,
        reviews_from_users: 76,
        reviews_from_critics: 0,
      },
    ],
  },
};
